/* automatically generated by rust-bindgen 0.72.1 */

pub type wchar_t = ::std::os::raw::c_int;

pub const PLVERSION: u32 = 100002;
pub const PLVERSION_TAG: &[u8; 1] = b"\0";
pub const PL_FLI_VERSION: u32 = 2;
pub const PL_REC_VERSION: u32 = 3;
pub const PL_QLF_LOADVERSION: u32 = 68;
pub const PL_QLF_VERSION: u32 = 71;
pub const HAVE_VISIBILITY_ATTRIBUTE: u32 = 1;
pub const TRUE: u32 = 1;
pub const FALSE: u32 = 0;
pub const PL_VARIABLE: u32 = 1;
pub const PL_ATOM: u32 = 2;
pub const PL_INTEGER: u32 = 3;
pub const PL_RATIONAL: u32 = 4;
pub const PL_FLOAT: u32 = 5;
pub const PL_STRING: u32 = 6;
pub const PL_TERM: u32 = 7;
pub const PL_NIL: u32 = 8;
pub const PL_BLOB: u32 = 9;
pub const PL_LIST_PAIR: u32 = 10;
pub const PL_FUNCTOR: u32 = 11;
pub const PL_LIST: u32 = 12;
pub const PL_CHARS: u32 = 13;
pub const PL_POINTER: u32 = 14;
pub const PL_CODE_LIST: u32 = 15;
pub const PL_CHAR_LIST: u32 = 16;
pub const PL_BOOL: u32 = 17;
pub const PL_FUNCTOR_CHARS: u32 = 18;
pub const _PL_PREDICATE_INDICATOR: u32 = 19;
pub const PL_SHORT: u32 = 20;
pub const PL_INT: u32 = 21;
pub const PL_LONG: u32 = 22;
pub const PL_DOUBLE: u32 = 23;
pub const PL_NCHARS: u32 = 24;
pub const PL_UTF8_CHARS: u32 = 25;
pub const PL_UTF8_STRING: u32 = 26;
pub const PL_INT64: u32 = 27;
pub const PL_NUTF8_CHARS: u32 = 28;
pub const PL_NUTF8_CODES: u32 = 29;
pub const PL_NUTF8_STRING: u32 = 30;
pub const PL_NWCHARS: u32 = 31;
pub const PL_NWCODES: u32 = 32;
pub const PL_NWSTRING: u32 = 33;
pub const PL_MBCHARS: u32 = 34;
pub const PL_MBCODES: u32 = 35;
pub const PL_MBSTRING: u32 = 36;
pub const PL_INTPTR: u32 = 37;
pub const PL_CHAR: u32 = 38;
pub const PL_CODE: u32 = 39;
pub const PL_BYTE: u32 = 40;
pub const PL_PARTIAL_LIST: u32 = 41;
pub const PL_CYCLIC_TERM: u32 = 42;
pub const PL_NOT_A_LIST: u32 = 43;
pub const PL_DICT: u32 = 44;
pub const PL_SWORD: u32 = 45;
pub const FF_READONLY: u32 = 4096;
pub const FF_KEEP: u32 = 8192;
pub const FF_NOCREATE: u32 = 16384;
pub const FF_FORCE: u32 = 32768;
pub const FF_LOCAL: u32 = 65536;
pub const FF_GLOBAL: u32 = 131072;
pub const PL_FIRST_CALL: u32 = 0;
pub const PL_CUTTED: u32 = 1;
pub const PL_PRUNED: u32 = 1;
pub const PL_REDO: u32 = 2;
pub const PL_RESUME: u32 = 3;
pub const PL_FA_NOTRACE: u32 = 1;
pub const PL_FA_TRANSPARENT: u32 = 2;
pub const PL_FA_NONDETERMINISTIC: u32 = 4;
pub const PL_FA_VARARGS: u32 = 8;
pub const PL_FA_CREF: u32 = 16;
pub const PL_FA_ISO: u32 = 32;
pub const PL_FA_META: u32 = 64;
pub const PL_FA_SIG_ATOMIC: u32 = 128;
pub const PL_Q_NORMAL: u32 = 2;
pub const PL_Q_NODEBUG: u32 = 4;
pub const PL_Q_CATCH_EXCEPTION: u32 = 8;
pub const PL_Q_PASS_EXCEPTION: u32 = 16;
pub const PL_Q_ALLOW_YIELD: u32 = 32;
pub const PL_Q_EXT_STATUS: u32 = 64;
pub const PL_Q_EXCEPT_HALT: u32 = 128;
pub const PL_Q_TRACE_WITH_YIELD: u32 = 256;
pub const PL_S_NOT_INNER: i32 = -2;
pub const PL_S_EXCEPTION: i32 = -1;
pub const PL_S_FALSE: u32 = 0;
pub const PL_S_TRUE: u32 = 1;
pub const PL_S_LAST: u32 = 2;
pub const PL_S_YIELD_DEBUG: u32 = 254;
pub const PL_S_YIELD: u32 = 255;
pub const PL_MAX_QUERY_DATA: u32 = 2;
pub const PL_ASSERTZ: u32 = 0;
pub const PL_ASSERTA: u32 = 1;
pub const PL_CREATE_THREAD_LOCAL: u32 = 16;
pub const PL_CREATE_INCREMENTAL: u32 = 32;
pub const PL_FOR_DICT_SORTED: u32 = 1;
pub const PL_BLOB_MAGIC_B: u32 = 1965636096;
pub const PL_BLOB_VERSION: u32 = 1;
pub const PL_BLOB_MAGIC: u32 = 1965636097;
pub const PL_BLOB_UNIQUE: u32 = 1;
pub const PL_BLOB_TEXT: u32 = 2;
pub const PL_BLOB_NOCOPY: u32 = 4;
pub const PL_BLOB_WCHAR: u32 = 8;
pub const PL_FILE_ABSOLUTE: u32 = 1;
pub const PL_FILE_OSPATH: u32 = 2;
pub const PL_FILE_SEARCH: u32 = 4;
pub const PL_FILE_EXIST: u32 = 8;
pub const PL_FILE_READ: u32 = 16;
pub const PL_FILE_WRITE: u32 = 32;
pub const PL_FILE_EXECUTE: u32 = 64;
pub const PL_FILE_NOERRORS: u32 = 128;
pub const CVT_ATOM: u32 = 1;
pub const CVT_STRING: u32 = 2;
pub const CVT_LIST: u32 = 4;
pub const CVT_INTEGER: u32 = 8;
pub const CVT_RATIONAL: u32 = 16;
pub const CVT_FLOAT: u32 = 32;
pub const CVT_VARIABLE: u32 = 64;
pub const CVT_NUMBER: u32 = 48;
pub const CVT_ATOMIC: u32 = 51;
pub const CVT_WRITE: u32 = 128;
pub const CVT_WRITE_CANONICAL: u32 = 256;
pub const CVT_WRITEQ: u32 = 512;
pub const CVT_ALL: u32 = 55;
pub const CVT_XINTEGER: u32 = 1032;
pub const CVT_MASK: u32 = 4095;
pub const CVT_EXCEPTION: u32 = 4096;
pub const CVT_VARNOFAIL: u32 = 8192;
pub const BUF_DISCARDABLE: u32 = 0;
pub const BUF_STACK: u32 = 65536;
pub const BUF_MALLOC: u32 = 131072;
pub const BUF_ALLOW_STACK: u32 = 262144;
pub const BUF_RING: u32 = 65536;
pub const REP_ISO_LATIN_1: u32 = 0;
pub const REP_UTF8: u32 = 1048576;
pub const REP_MB: u32 = 2097152;
pub const REP_FN: u32 = 2097152;
pub const PL_DIFF_LIST: u32 = 16777216;
pub const PL_WRT_QUOTED: u32 = 1;
pub const PL_WRT_IGNOREOPS: u32 = 2;
pub const PL_WRT_NUMBERVARS: u32 = 4;
pub const PL_WRT_PORTRAY: u32 = 8;
pub const PL_WRT_CHARESCAPES: u32 = 16;
pub const PL_WRT_BACKQUOTED_STRING: u32 = 32;
pub const PL_WRT_ATTVAR_IGNORE: u32 = 64;
pub const PL_WRT_ATTVAR_DOTS: u32 = 128;
pub const PL_WRT_ATTVAR_WRITE: u32 = 256;
pub const PL_WRT_ATTVAR_PORTRAY: u32 = 512;
pub const PL_WRT_ATTVAR_MASK: u32 = 960;
pub const PL_WRT_BLOB_PORTRAY: u32 = 1024;
pub const PL_WRT_NO_CYCLES: u32 = 2048;
pub const PL_WRT_NEWLINE: u32 = 8192;
pub const PL_WRT_VARNAMES: u32 = 16384;
pub const PL_WRT_BACKQUOTE_IS_SYMBOL: u32 = 32768;
pub const PL_WRT_DOTLISTS: u32 = 65536;
pub const PL_WRT_BRACETERMS: u32 = 131072;
pub const PL_WRT_NODICT: u32 = 262144;
pub const PL_WRT_NODOTINATOM: u32 = 524288;
pub const PL_WRT_NO_LISTS: u32 = 1048576;
pub const PL_WRT_RAT_NATURAL: u32 = 2097152;
pub const PL_WRT_CHARESCAPES_UNICODE: u32 = 4194304;
pub const PL_WRT_QUOTE_NON_ASCII: u32 = 8388608;
pub const PL_WRT_PARTIAL: u32 = 16777216;
pub const PL_WRT_NO_CHARESCAPES: u32 = 33554432;
pub const PL_WRT_INFIX_COMMA: u32 = 67108864;
pub const PL_WRT_PORTABLE: u32 = 67108866;
pub const PL_NOTTY: u32 = 0;
pub const PL_RAWTTY: u32 = 1;
pub const PL_COOKEDTTY: u32 = 2;
pub const PL_CLEANUP_STATUS_MASK: u32 = 65535;
pub const PL_CLEANUP_NO_RECLAIM_MEMORY: u32 = 65536;
pub const PL_CLEANUP_NO_CANCEL: u32 = 131072;
pub const PL_HALT_WITH_EXCEPTION: u32 = 262144;
pub const PL_CLEANUP_CANCELED: u32 = 0;
pub const PL_CLEANUP_SUCCESS: u32 = 1;
pub const PL_CLEANUP_FAILED: i32 = -1;
pub const PL_CLEANUP_RECURSIVE: i32 = -2;
pub const PL_DISPATCH_NOWAIT: u32 = 0;
pub const PL_DISPATCH_WAIT: u32 = 1;
pub const PL_DISPATCH_INSTALLED: u32 = 2;
pub const PL_DISPATCH_INPUT: u32 = 0;
pub const PL_DISPATCH_TIMEOUT: u32 = 1;
pub const OPT_TYPE_MASK: u32 = 255;
pub const OPT_INF: u32 = 256;
pub const OPT_UNKNOWN_DEFAULT: u32 = 0;
pub const OPT_UNKNOWN_ERROR: u32 = 1;
pub const OPT_UNKNOWN_IGNORE: u32 = 2;
pub const OPT_UNKNOWN_WARNING: u32 = 3;
pub const OPT_UNKNOWN_MASK: u32 = 3;
pub const OPT_ALL: u32 = 1;
pub const PL_SIGSYNC: u32 = 65536;
pub const PL_SIGNOFRAME: u32 = 131072;
pub const PLSIG_THROW: u32 = 2;
pub const PLSIG_SYNC: u32 = 4;
pub const PLSIG_NOFRAME: u32 = 8;
pub const PLSIG_IGNORE: u32 = 16;
pub const PL_ACTION_TRACE: u32 = 1;
pub const PL_ACTION_DEBUG: u32 = 2;
pub const PL_ACTION_BACKTRACE: u32 = 3;
pub const PL_ACTION_BREAK: u32 = 4;
pub const PL_ACTION_HALT: u32 = 5;
pub const PL_ACTION_ABORT: u32 = 6;
pub const PL_ACTION_WRITE: u32 = 8;
pub const PL_ACTION_FLUSH: u32 = 9;
pub const PL_ACTION_GUIAPP: u32 = 10;
pub const PL_ACTION_ATTACH_CONSOLE: u32 = 11;
pub const PL_GMP_SET_ALLOC_FUNCTIONS: u32 = 12;
pub const PL_ACTION_TRADITIONAL: u32 = 13;
pub const PL_BT_SAFE: u32 = 1;
pub const PL_BT_USER: u32 = 2;
pub const PL_VERSION_SYSTEM: u32 = 1;
pub const PL_VERSION_FLI: u32 = 2;
pub const PL_VERSION_REC: u32 = 3;
pub const PL_VERSION_QLF: u32 = 4;
pub const PL_VERSION_QLF_LOAD: u32 = 5;
pub const PL_VERSION_VM: u32 = 6;
pub const PL_VERSION_BUILT_IN: u32 = 7;
pub const PL_QUERY_ARGC: u32 = 1;
pub const PL_QUERY_ARGV: u32 = 2;
pub const PL_QUERY_GETC: u32 = 5;
pub const PL_QUERY_MAX_INTEGER: u32 = 6;
pub const PL_QUERY_MIN_INTEGER: u32 = 7;
pub const PL_QUERY_MAX_TAGGED_INT: u32 = 8;
pub const PL_QUERY_MIN_TAGGED_INT: u32 = 9;
pub const PL_QUERY_VERSION: u32 = 10;
pub const PL_QUERY_MAX_THREADS: u32 = 11;
pub const PL_QUERY_ENCODING: u32 = 12;
pub const PL_QUERY_USER_CPU: u32 = 13;
pub const PL_QUERY_HALTING: u32 = 14;
pub const PL_THREAD_NO_DEBUG: u32 = 1;
pub const PL_THREAD_NOT_DETACHED: u32 = 2;
pub const PL_THREAD_CUR_STREAMS: u32 = 4;
pub const PL_ENGINE_SET: u32 = 0;
pub const PL_ENGINE_INVAL: u32 = 2;
pub const PL_ENGINE_INUSE: u32 = 3;
pub const PL_HT_NEW: u32 = 1;
pub const PL_HT_UPDATE: u32 = 2;
pub const PL_ARITY_AS_SIZE: u32 = 1;
pub type __PL_word = u64;
pub type atom_t = usize;
pub type functor_t = usize;
pub type __PL_code = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_module {
    _unused: [u8; 0],
}
pub type module_t = *mut __PL_module;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_procedure {
    _unused: [u8; 0],
}
pub type predicate_t = *mut __PL_procedure;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_record {
    _unused: [u8; 0],
}
pub type record_t = *mut __PL_record;
pub type term_t = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_queryRef {
    _unused: [u8; 0],
}
pub type qid_t = *mut __PL_queryRef;
pub type PL_fid_t = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_foreign_context {
    _unused: [u8; 0],
}
pub type control_t = *mut __PL_foreign_context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_PL_local_data {
    _unused: [u8; 0],
}
pub type PL_engine_t = *mut __PL_PL_local_data;
pub type PL_atomic_t = __PL_word;
pub type foreign_t = usize;
pub type pl_wchar_t = wchar_t;
pub type pl_function_t = *mut ::std::os::raw::c_void;
pub type buf_mark_t = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct io_stream {
    _unused: [u8; 0],
}
pub type IOSTREAM = io_stream;
#[repr(C)]
#[derive(Copy, Clone)]
pub union term_value_t {
    pub i: i64,
    pub f: f64,
    pub s: *mut ::std::os::raw::c_char,
    pub a: atom_t,
    pub t: term_value_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct term_value_t__bindgen_ty_1 {
    pub name: atom_t,
    pub arity: usize,
}
unsafe extern "C" {
    pub fn _PL_retry(arg1: isize) -> foreign_t;
}
unsafe extern "C" {
    pub fn _PL_retry_address(arg1: *mut ::std::os::raw::c_void) -> foreign_t;
}
unsafe extern "C" {
    pub fn _PL_yield_address(arg1: *mut ::std::os::raw::c_void) -> foreign_t;
}
unsafe extern "C" {
    pub fn PL_foreign_control(arg1: control_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_foreign_context(arg1: control_t) -> isize;
}
unsafe extern "C" {
    pub fn PL_foreign_context_address(arg1: control_t) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_foreign_context_predicate(arg1: control_t) -> predicate_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PL_extension {
    pub predicate_name: *const ::std::os::raw::c_char,
    pub arity: ::std::os::raw::c_short,
    pub function: pl_function_t,
    pub flags: ::std::os::raw::c_short,
}
unsafe extern "C" {
    pub static mut PL_extensions: [PL_extension; 0usize];
}
unsafe extern "C" {
    pub fn PL_register_extensions(e: *const PL_extension);
}
unsafe extern "C" {
    pub fn PL_register_extensions_in_module(
        module: *const ::std::os::raw::c_char,
        e: *const PL_extension,
    );
}
unsafe extern "C" {
    pub fn PL_register_foreign(
        name: *const ::std::os::raw::c_char,
        arity: ::std::os::raw::c_int,
        func: pl_function_t,
        flags: ::std::os::raw::c_int,
        ...
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_register_foreign_in_module(
        module: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        arity: ::std::os::raw::c_int,
        func: pl_function_t,
        flags: ::std::os::raw::c_int,
        ...
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_load_extensions(e: *const PL_extension);
}
unsafe extern "C" {
    pub fn PL_license(
        license: *const ::std::os::raw::c_char,
        module: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn PL_context() -> module_t;
}
unsafe extern "C" {
    pub fn PL_module_name(module: module_t) -> atom_t;
}
unsafe extern "C" {
    pub fn PL_new_module(name: atom_t) -> module_t;
}
unsafe extern "C" {
    pub fn PL_strip_module(in_: term_t, m: *mut module_t, out: term_t) -> bool;
}
unsafe extern "C" {
    pub fn _PL_atoms() -> *const atom_t;
}
unsafe extern "C" {
    pub fn PL_open_foreign_frame() -> PL_fid_t;
}
unsafe extern "C" {
    pub fn PL_rewind_foreign_frame(cid: PL_fid_t);
}
unsafe extern "C" {
    pub fn PL_close_foreign_frame(cid: PL_fid_t);
}
unsafe extern "C" {
    pub fn PL_discard_foreign_frame(cid: PL_fid_t);
}
unsafe extern "C" {
    pub fn PL_pred(f: functor_t, m: module_t) -> predicate_t;
}
unsafe extern "C" {
    pub fn PL_predicate(
        name: *const ::std::os::raw::c_char,
        arity: ::std::os::raw::c_int,
        module: *const ::std::os::raw::c_char,
    ) -> predicate_t;
}
unsafe extern "C" {
    pub fn PL_predicate_info(
        pred: predicate_t,
        name: *mut atom_t,
        arity: *mut usize,
        module: *mut module_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_open_query(
        m: module_t,
        flags: ::std::os::raw::c_int,
        pred: predicate_t,
        t0: term_t,
    ) -> qid_t;
}
unsafe extern "C" {
    pub fn PL_next_solution(qid: qid_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_close_query(qid: qid_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_cut_query(qid: qid_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_current_query() -> qid_t;
}
unsafe extern "C" {
    pub fn PL_query_engine(qid: qid_t) -> PL_engine_t;
}
unsafe extern "C" {
    pub fn PL_query_arguments(qid: qid_t) -> term_t;
}
unsafe extern "C" {
    pub fn PL_can_yield() -> bool;
}
unsafe extern "C" {
    pub fn PL_set_query_data(
        qid: qid_t,
        offset: ::std::os::raw::c_uint,
        data: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_query_data(qid: qid_t, offset: ::std::os::raw::c_uint)
        -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_call(t: term_t, m: module_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_call_predicate(
        m: module_t,
        flags: ::std::os::raw::c_int,
        pred: predicate_t,
        t0: term_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_exception(qid: qid_t) -> term_t;
}
unsafe extern "C" {
    pub fn PL_raise_exception(exception: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_throw(exception: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_clear_exception();
}
unsafe extern "C" {
    pub fn PL_yielded(qid: qid_t) -> term_t;
}
unsafe extern "C" {
    pub fn PL_set_trace_action(action: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_trace_context(goal: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_assert(term: term_t, m: module_t, flags: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_new_term_refs(n: usize) -> term_t;
}
unsafe extern "C" {
    pub fn PL_new_term_ref() -> term_t;
}
unsafe extern "C" {
    pub fn PL_copy_term_ref(from: term_t) -> term_t;
}
unsafe extern "C" {
    pub fn PL_free_term_ref(t: term_t);
}
unsafe extern "C" {
    pub fn PL_reset_term_refs(r: term_t);
}
unsafe extern "C" {
    pub fn PL_new_atom(s: *const ::std::os::raw::c_char) -> atom_t;
}
unsafe extern "C" {
    pub fn PL_new_atom_nchars(len: usize, s: *const ::std::os::raw::c_char) -> atom_t;
}
unsafe extern "C" {
    pub fn PL_new_atom_wchars(len: usize, s: *const pl_wchar_t) -> atom_t;
}
unsafe extern "C" {
    pub fn PL_new_atom_mbchars(
        rep: ::std::os::raw::c_int,
        len: usize,
        s: *const ::std::os::raw::c_char,
    ) -> atom_t;
}
unsafe extern "C" {
    pub fn PL_atom_chars(a: atom_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_atom_nchars(a: atom_t, len: *mut usize) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_atom_mbchars(
        a: atom_t,
        len: *mut usize,
        s: *mut *mut ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_atom_wchars(a: atom_t, len: *mut usize) -> *const wchar_t;
}
unsafe extern "C" {
    pub fn PL_register_atom(a: atom_t);
}
unsafe extern "C" {
    pub fn PL_unregister_atom(a: atom_t);
}
unsafe extern "C" {
    pub fn PL_atom_index(index: atom_t) -> usize;
}
unsafe extern "C" {
    pub fn PL_atom_from_index(a: usize) -> atom_t;
}
unsafe extern "C" {
    pub fn PL_new_functor_sz(f: atom_t, a: usize) -> functor_t;
}
unsafe extern "C" {
    pub fn PL_new_functor(f: atom_t, a: ::std::os::raw::c_int) -> functor_t;
}
unsafe extern "C" {
    pub fn PL_functor_name(f: functor_t) -> atom_t;
}
unsafe extern "C" {
    pub fn PL_functor_arity(f: functor_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_functor_arity_sz(f: functor_t) -> usize;
}
unsafe extern "C" {
    pub fn PL_get_atom(t: term_t, a: *mut atom_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_bool(t: term_t, value: *mut ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_atom_chars(t: term_t, a: *mut *mut ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_string(t: term_t, s: *mut *mut ::std::os::raw::c_char, len: *mut usize) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_chars(
        t: term_t,
        s: *mut *mut ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_list_chars(
        l: term_t,
        s: *mut *mut ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_atom_nchars(
        t: term_t,
        len: *mut usize,
        a: *mut *mut ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_list_nchars(
        l: term_t,
        len: *mut usize,
        s: *mut *mut ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_nchars(
        t: term_t,
        len: *mut usize,
        s: *mut *mut ::std::os::raw::c_char,
        flags: ::std::os::raw::c_uint,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_integer(t: term_t, i: *mut ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_long(t: term_t, i: *mut ::std::os::raw::c_long) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_intptr(t: term_t, i: *mut isize) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_pointer(t: term_t, ptr: *mut *mut ::std::os::raw::c_void) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_float(t: term_t, f: *mut f64) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_functor(t: term_t, f: *mut functor_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_name_arity_sz(t: term_t, name: *mut atom_t, arity: *mut usize) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_compound_name_arity_sz(t: term_t, name: *mut atom_t, arity: *mut usize) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_name_arity(
        t: term_t,
        name: *mut atom_t,
        arity: *mut ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_compound_name_arity(
        t: term_t,
        name: *mut atom_t,
        arity: *mut ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_module(t: term_t, module: *mut module_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_arg_sz(index: usize, t: term_t, a: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_arg(index: ::std::os::raw::c_int, t: term_t, a: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_dict_key(key: atom_t, dict: term_t, value: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_list(l: term_t, h: term_t, t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_head(l: term_t, h: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_tail(l: term_t, t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_nil(l: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_term_value(t: term_t, v: *mut term_value_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_quote(
        chr: ::std::os::raw::c_int,
        data: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_for_dict(
        dict: term_t,
        func: ::std::option::Option<
            unsafe extern "C" fn(
                key: term_t,
                value: term_t,
                closure: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        closure: *mut ::std::os::raw::c_void,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_term_type(t: term_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_is_variable(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_ground(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_atom(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_integer(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_string(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_float(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_rational(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_compound(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_callable(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_functor(t: term_t, f: functor_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_list(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_dict(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_pair(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_atomic(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_number(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_acyclic(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_variable(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_atom(t: term_t, a: atom_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_bool(t: term_t, val: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_atom_chars(t: term_t, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_string_chars(t: term_t, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_chars(
        t: term_t,
        flags: ::std::os::raw::c_int,
        len: usize,
        chars: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_list_chars(t: term_t, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_list_codes(t: term_t, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_atom_nchars(t: term_t, l: usize, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_string_nchars(
        t: term_t,
        len: usize,
        chars: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_list_nchars(t: term_t, l: usize, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_list_ncodes(t: term_t, l: usize, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_integer(t: term_t, i: ::std::os::raw::c_long) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_pointer(t: term_t, ptr: *mut ::std::os::raw::c_void) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_float(t: term_t, f: f64) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_functor(t: term_t, functor: functor_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_list(l: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_nil(l: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_term(t1: term_t, t2: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_dict(
        t: term_t,
        tag: atom_t,
        len: usize,
        keys: *const atom_t,
        values: term_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn _PL_cons_small_int(v: i64) -> atom_t;
}
unsafe extern "C" {
    pub fn _PL_unregister_keys(len: usize, keys: *mut atom_t);
}
unsafe extern "C" {
    pub fn PL_cons_functor(h: term_t, f: functor_t, ...) -> bool;
}
unsafe extern "C" {
    pub fn PL_cons_functor_v(h: term_t, fd: functor_t, a0: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_cons_list(l: term_t, h: term_t, t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify(t1: term_t, t2: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_atom(t: term_t, a: atom_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_atom_chars(t: term_t, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_list_chars(t: term_t, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_list_codes(t: term_t, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_string_chars(t: term_t, chars: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_atom_nchars(t: term_t, l: usize, s: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_list_ncodes(t: term_t, l: usize, s: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_list_nchars(t: term_t, l: usize, s: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_string_nchars(
        t: term_t,
        len: usize,
        chars: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_bool(t: term_t, n: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_integer(t: term_t, n: isize) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_float(t: term_t, f: f64) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_pointer(t: term_t, ptr: *mut ::std::os::raw::c_void) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_functor(t: term_t, f: functor_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_compound(t: term_t, f: functor_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_list(l: term_t, h: term_t, t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_nil(l: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_arg_sz(index: usize, t: term_t, a: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_arg(index: ::std::os::raw::c_int, t: term_t, a: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_term(t: term_t, ...) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_chars(
        t: term_t,
        flags: ::std::os::raw::c_int,
        len: usize,
        s: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_skip_list(list: term_t, tail: term_t, len: *mut usize) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_put_wchars(
        t: term_t,
        type_: ::std::os::raw::c_int,
        len: usize,
        s: *const pl_wchar_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_wchars(
        t: term_t,
        type_: ::std::os::raw::c_int,
        len: usize,
        s: *const pl_wchar_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_wchars_diff(
        t: term_t,
        tail: term_t,
        type_: ::std::os::raw::c_int,
        len: usize,
        s: *const pl_wchar_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_wchars(
        l: term_t,
        length: *mut usize,
        s: *mut *mut pl_wchar_t,
        flags: ::std::os::raw::c_uint,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_utf8_strlen(s: *const ::std::os::raw::c_char, len: usize) -> usize;
}
unsafe extern "C" {
    pub fn PL_get_int64(t: term_t, i: *mut i64) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_uint64(t: term_t, i: *mut u64) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_int64(t: term_t, value: i64) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_uint64(t: term_t, value: u64) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_int64(t: term_t, i: i64) -> bool;
}
unsafe extern "C" {
    pub fn PL_put_uint64(t: term_t, i: u64) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_attvar(t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_attr(v: term_t, a: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_delay_list(l: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_atom_ex(t: term_t, a: *mut atom_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_integer_ex(t: term_t, i: *mut ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_long_ex(t: term_t, i: *mut ::std::os::raw::c_long) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_int64_ex(t: term_t, i: *mut i64) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_uint64_ex(t: term_t, i: *mut u64) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_intptr_ex(t: term_t, i: *mut isize) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_size_ex(t: term_t, i: *mut usize) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_bool_ex(t: term_t, i: *mut ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_float_ex(t: term_t, f: *mut f64) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_char_ex(
        t: term_t,
        p: *mut ::std::os::raw::c_int,
        eof: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_bool_ex(t: term_t, val: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_pointer_ex(t: term_t, addrp: *mut *mut ::std::os::raw::c_void) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_list_ex(l: term_t, h: term_t, t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_nil_ex(l: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_list_ex(l: term_t, h: term_t, t: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_nil_ex(l: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_instantiation_error(culprit: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_uninstantiation_error(culprit: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_representation_error(resource: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_type_error(expected: *const ::std::os::raw::c_char, culprit: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_domain_error(expected: *const ::std::os::raw::c_char, culprit: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_existence_error(type_: *const ::std::os::raw::c_char, culprit: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_permission_error(
        operation: *const ::std::os::raw::c_char,
        type_: *const ::std::os::raw::c_char,
        culprit: term_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_resource_error(resource: *const ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_syntax_error(msg: *const ::std::os::raw::c_char, in_: *mut IOSTREAM) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PL_blob_t {
    pub magic: usize,
    pub flags: usize,
    pub name: *const ::std::os::raw::c_char,
    pub release: ::std::option::Option<unsafe extern "C" fn(a: atom_t) -> ::std::os::raw::c_int>,
    pub compare:
        ::std::option::Option<unsafe extern "C" fn(a: atom_t, b: atom_t) -> ::std::os::raw::c_int>,
    pub write: ::std::option::Option<
        unsafe extern "C" fn(
            s: *mut IOSTREAM,
            a: atom_t,
            flags: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub acquire: ::std::option::Option<unsafe extern "C" fn(a: atom_t)>,
    pub save: ::std::option::Option<
        unsafe extern "C" fn(a: atom_t, s: *mut IOSTREAM) -> ::std::os::raw::c_int,
    >,
    pub load: ::std::option::Option<unsafe extern "C" fn(s: *mut IOSTREAM) -> atom_t>,
    pub padding: usize,
    pub reserved: [*mut ::std::os::raw::c_void; 8usize],
    pub write_ex: ::std::option::Option<
        unsafe extern "C" fn(
            a: atom_t,
            context: *mut ::std::os::raw::c_void,
        ) -> ::std::os::raw::c_int,
    >,
    pub registered: bool,
    pub rank: ::std::os::raw::c_int,
    pub next: *mut PL_blob_t,
    pub atom_name: atom_t,
}
unsafe extern "C" {
    pub fn PL_is_blob(t: term_t, type_: *mut *mut PL_blob_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_unify_blob(
        t: term_t,
        blob: *mut ::std::os::raw::c_void,
        len: usize,
        type_: *mut PL_blob_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_new_blob(
        blob: *mut ::std::os::raw::c_void,
        len: usize,
        type_: *mut PL_blob_t,
    ) -> atom_t;
}
unsafe extern "C" {
    pub fn PL_put_blob(
        t: term_t,
        blob: *mut ::std::os::raw::c_void,
        len: usize,
        type_: *mut PL_blob_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_blob(
        t: term_t,
        blob: *mut *mut ::std::os::raw::c_void,
        len: *mut usize,
        type_: *mut *mut PL_blob_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_blob_data(
        a: atom_t,
        len: *mut usize,
        type_: *mut *mut PL_blob_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_free_blob(blob: atom_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_register_blob_type(type_: *mut PL_blob_t);
}
unsafe extern "C" {
    pub fn PL_find_blob_type(name: *const ::std::os::raw::c_char) -> *mut PL_blob_t;
}
unsafe extern "C" {
    pub fn PL_unregister_blob_type(type_: *mut PL_blob_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_file_name(
        n: term_t,
        name: *mut *mut ::std::os::raw::c_char,
        flags: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_file_nameW(
        n: term_t,
        name: *mut *mut wchar_t,
        flags: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_changed_cwd();
}
unsafe extern "C" {
    pub fn PL_cwd(buf: *mut ::std::os::raw::c_char, buflen: usize) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_cvt_i_bool(p: term_t, c: *mut ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_char(p: term_t, c: *mut ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_schar(p: term_t, c: *mut ::std::os::raw::c_schar) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_uchar(p: term_t, c: *mut ::std::os::raw::c_uchar) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_short(p: term_t, s: *mut ::std::os::raw::c_short) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_ushort(p: term_t, s: *mut ::std::os::raw::c_ushort) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_int(p: term_t, c: *mut ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_uint(p: term_t, c: *mut ::std::os::raw::c_uint) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_long(p: term_t, c: *mut ::std::os::raw::c_long) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_ulong(p: term_t, c: *mut ::std::os::raw::c_ulong) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_llong(p: term_t, c: *mut ::std::os::raw::c_longlong) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_ullong(p: term_t, c: *mut ::std::os::raw::c_ulonglong) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_int32(p: term_t, c: *mut i32) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_uint32(p: term_t, c: *mut u32) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_int64(p: term_t, c: *mut i64) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_uint64(p: term_t, c: *mut u64) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_size_t(p: term_t, c: *mut usize) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_float(p: term_t, c: *mut f64) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_single(p: term_t, c: *mut f32) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_string(p: term_t, c: *mut *mut ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_codes(p: term_t, c: *mut *mut ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_atom(p: term_t, c: *mut atom_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_i_address(p: term_t, c: *mut ::std::os::raw::c_void) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_o_int64(c: i64, p: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_o_float(c: f64, p: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_o_single(c: f32, p: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_o_string(c: *const ::std::os::raw::c_char, p: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_o_codes(c: *const ::std::os::raw::c_char, p: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_o_atom(c: atom_t, p: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_cvt_o_address(address: *mut ::std::os::raw::c_void, p: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_new_nil_ref() -> term_t;
}
unsafe extern "C" {
    pub fn PL_cvt_encoding() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_cvt_set_encoding(enc: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn SP_set_state(state: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn SP_get_state() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_compare(t1: term_t, t2: term_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_same_compound(t1: term_t, t2: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_warning(fmt: *const ::std::os::raw::c_char, ...) -> bool;
}
unsafe extern "C" {
    pub fn PL_warningX(fmt: *const ::std::os::raw::c_char, ...) -> bool;
}
unsafe extern "C" {
    pub fn PL_fatal_error(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn PL_api_error(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn PL_system_error(fmt: *const ::std::os::raw::c_char, ...);
}
unsafe extern "C" {
    pub fn PL_print_message(severity: atom_t, ...) -> bool;
}
unsafe extern "C" {
    pub fn PL_record(term: term_t) -> record_t;
}
unsafe extern "C" {
    pub fn PL_recorded(record: record_t, term: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_erase(record: record_t);
}
unsafe extern "C" {
    pub fn PL_duplicate_record(r: record_t) -> record_t;
}
unsafe extern "C" {
    pub fn PL_record_external(t: term_t, size: *mut usize) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_recorded_external(rec: *const ::std::os::raw::c_char, term: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_erase_external(rec: *mut ::std::os::raw::c_char) -> bool;
}
unsafe extern "C" {
    pub fn PL_set_prolog_flag(
        name: *const ::std::os::raw::c_char,
        type_: ::std::os::raw::c_int,
        ...
    ) -> bool;
}
unsafe extern "C" {
    pub fn _PL_get_atomic(t: term_t) -> PL_atomic_t;
}
unsafe extern "C" {
    pub fn _PL_put_atomic(t: term_t, a: PL_atomic_t);
}
unsafe extern "C" {
    pub fn PL_unify_atomic(t: term_t, a: PL_atomic_t) -> bool;
}
unsafe extern "C" {
    pub fn _PL_get_arg_sz(index: usize, t: term_t, a: term_t) -> bool;
}
unsafe extern "C" {
    pub fn _PL_get_arg(index: ::std::os::raw::c_int, t: term_t, a: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_mark_string_buffers(mark: *mut buf_mark_t);
}
unsafe extern "C" {
    pub fn PL_release_string_buffers_from_mark(mark: buf_mark_t);
}
unsafe extern "C" {
    pub fn PL_unify_stream(t: term_t, s: *mut IOSTREAM) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_stream_handle(t: term_t, s: *mut *mut IOSTREAM) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_stream(t: term_t, s: *mut *mut IOSTREAM, flags: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_stream_from_blob(
        a: atom_t,
        s: *mut *mut IOSTREAM,
        flags: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_acquire_stream(s: *mut IOSTREAM) -> *mut IOSTREAM;
}
unsafe extern "C" {
    pub fn PL_release_stream(s: *mut IOSTREAM) -> bool;
}
unsafe extern "C" {
    pub fn PL_release_stream_noerror(s: *mut IOSTREAM) -> bool;
}
unsafe extern "C" {
    pub fn PL_open_resource(
        m: module_t,
        name: *const ::std::os::raw::c_char,
        rc_class: *const ::std::os::raw::c_char,
        mode: *const ::std::os::raw::c_char,
    ) -> *mut IOSTREAM;
}
unsafe extern "C" {
    pub fn _PL_streams() -> *mut *mut IOSTREAM;
}
unsafe extern "C" {
    pub fn _PL_stream(which: ::std::os::raw::c_int) -> *mut IOSTREAM;
}
unsafe extern "C" {
    pub fn PL_write_term(
        s: *mut IOSTREAM,
        term: term_t,
        precedence: ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_ttymode(s: *mut IOSTREAM) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_put_term_from_chars(
        t: term_t,
        flags: ::std::os::raw::c_int,
        len: usize,
        s: *const ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_chars_to_term(chars: *const ::std::os::raw::c_char, term: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_wchars_to_term(chars: *const pl_wchar_t, term: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_initialise(
        argc: ::std::os::raw::c_int,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_winitialise(argc: ::std::os::raw::c_int, argv: *mut *mut wchar_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_is_initialised(
        argc: *mut ::std::os::raw::c_int,
        argv: *mut *mut *mut ::std::os::raw::c_char,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_set_resource_db_mem(data: *const ::std::os::raw::c_uchar, size: usize) -> bool;
}
unsafe extern "C" {
    pub fn PL_toplevel() -> bool;
}
unsafe extern "C" {
    pub fn PL_cleanup(status: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_cleanup_fork();
}
unsafe extern "C" {
    pub fn PL_halt(status: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_dlopen(
        file: *const ::std::os::raw::c_char,
        flags: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_dlerror() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_dlsym(
        handle: *mut ::std::os::raw::c_void,
        symbol: *mut ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_dlclose(handle: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_add_to_protocol(buf: *const ::std::os::raw::c_char, count: usize);
}
unsafe extern "C" {
    pub fn PL_prompt_string(in_: *mut IOSTREAM) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_write_prompt(dowrite: bool);
}
unsafe extern "C" {
    pub fn PL_prompt_next(in_: *mut IOSTREAM);
}
unsafe extern "C" {
    pub fn PL_atom_generator(
        prefix: *const ::std::os::raw::c_char,
        state: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_atom_generator_w(
        pref: *const pl_wchar_t,
        buffer: *mut pl_wchar_t,
        buflen: usize,
        state: ::std::os::raw::c_int,
    ) -> *mut pl_wchar_t;
}
unsafe extern "C" {
    pub fn PL_malloc(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_malloc_atomic(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_malloc_uncollectable(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_malloc_atomic_uncollectable(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_realloc(mem: *mut ::std::os::raw::c_void, size: usize)
        -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_malloc_unmanaged(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_malloc_atomic_unmanaged(size: usize) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_free(mem: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn PL_linger(mem: *mut ::std::os::raw::c_void) -> bool;
}
pub type PL_dispatch_hook_t =
    ::std::option::Option<unsafe extern "C" fn(fd: *mut IOSTREAM) -> ::std::os::raw::c_int>;
pub type PL_abort_hook_t = ::std::option::Option<unsafe extern "C" fn()>;
pub type PL_initialise_hook_t = ::std::option::Option<
    unsafe extern "C" fn(argc: ::std::os::raw::c_int, argv: *mut *mut ::std::os::raw::c_char),
>;
pub type PL_agc_hook_t =
    ::std::option::Option<unsafe extern "C" fn(a: atom_t) -> ::std::os::raw::c_int>;
unsafe extern "C" {
    pub fn PL_dispatch(fd: *mut IOSTREAM, wait: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_dispatch_hook(arg1: PL_dispatch_hook_t) -> PL_dispatch_hook_t;
}
unsafe extern "C" {
    pub fn PL_abort_hook(arg1: PL_abort_hook_t);
}
unsafe extern "C" {
    pub fn PL_initialise_hook(arg1: PL_initialise_hook_t);
}
unsafe extern "C" {
    pub fn PL_abort_unhook(arg1: PL_abort_hook_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_agc_hook(arg1: PL_agc_hook_t) -> PL_agc_hook_t;
}
pub const _PL_opt_enum_t__OPT_END: _PL_opt_enum_t = -1;
pub const _PL_opt_enum_t_OPT_BOOL: _PL_opt_enum_t = 0;
pub const _PL_opt_enum_t_OPT_INT: _PL_opt_enum_t = 1;
pub const _PL_opt_enum_t_OPT_INT64: _PL_opt_enum_t = 2;
pub const _PL_opt_enum_t_OPT_UINT64: _PL_opt_enum_t = 3;
pub const _PL_opt_enum_t_OPT_SIZE: _PL_opt_enum_t = 4;
pub const _PL_opt_enum_t_OPT_DOUBLE: _PL_opt_enum_t = 5;
pub const _PL_opt_enum_t_OPT_STRING: _PL_opt_enum_t = 6;
pub const _PL_opt_enum_t_OPT_ATOM: _PL_opt_enum_t = 7;
pub const _PL_opt_enum_t_OPT_TERM: _PL_opt_enum_t = 8;
pub const _PL_opt_enum_t_OPT_LOCALE: _PL_opt_enum_t = 9;
pub type _PL_opt_enum_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PL_option_t {
    pub name: atom_t,
    pub type_: _PL_opt_enum_t,
    pub string: *const ::std::os::raw::c_char,
}
unsafe extern "C" {
    pub fn PL_scan_options(
        options: term_t,
        flags: ::std::os::raw::c_int,
        opttype: *const ::std::os::raw::c_char,
        specs: *mut PL_option_t,
        ...
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pl_sigaction {
    pub sa_cfunction: ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>,
    pub sa_predicate: predicate_t,
    pub sa_flags: ::std::os::raw::c_int,
    pub reserved: [*mut ::std::os::raw::c_void; 2usize],
}
pub type pl_sigaction_t = pl_sigaction;
unsafe extern "C" {
    pub fn PL_signal(
        sig: ::std::os::raw::c_int,
        func: ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>,
    ) -> ::std::option::Option<
        unsafe extern "C" fn(
            sig: ::std::os::raw::c_int,
            func: ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>,
        ),
    >;
}
unsafe extern "C" {
    pub fn PL_sigaction(
        sig: ::std::os::raw::c_int,
        act: *mut pl_sigaction_t,
        old: *mut pl_sigaction_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_interrupt(sig: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn PL_raise(sig: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_handle_signals() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_get_signum_ex(sig: term_t, n: *mut ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_action(arg1: ::std::os::raw::c_int, ...) -> bool;
}
unsafe extern "C" {
    pub fn PL_on_halt(
        arg1: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: ::std::os::raw::c_int,
                arg2: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        arg2: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn PL_exit_hook(
        arg1: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: ::std::os::raw::c_int,
                arg2: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        arg2: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn PL_backtrace(depth: ::std::os::raw::c_int, flags: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn PL_backtrace_string(
        depth: ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn PL_check_data(data: term_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_check_stacks() -> bool;
}
unsafe extern "C" {
    pub fn PL_current_prolog_flag(
        name: atom_t,
        type_: ::std::os::raw::c_int,
        ptr: *mut ::std::os::raw::c_void,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_version_info(which: ::std::os::raw::c_int) -> ::std::os::raw::c_uint;
}
unsafe extern "C" {
    pub fn PL_query(arg1: ::std::os::raw::c_int) -> isize;
}
pub const rc_cancel_PL_THREAD_CANCEL_FAILED: rc_cancel = 0;
pub const rc_cancel_PL_THREAD_CANCEL_JOINED: rc_cancel = 1;
pub const rc_cancel_PL_THREAD_CANCEL_MUST_JOIN: rc_cancel = 2;
pub type rc_cancel = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PL_thread_attr_t {
    pub stack_limit: usize,
    pub table_space: usize,
    pub alias: *mut ::std::os::raw::c_char,
    pub cancel: ::std::option::Option<unsafe extern "C" fn(id: ::std::os::raw::c_int) -> rc_cancel>,
    pub flags: isize,
    pub max_queue_size: usize,
    pub thread_class: *mut ::std::os::raw::c_char,
    pub reserved: [*mut ::std::os::raw::c_void; 2usize],
}
unsafe extern "C" {
    pub fn PL_thread_self() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_unify_thread_id(t: term_t, i: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_get_thread_id_ex(t: term_t, idp: *mut ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_get_thread_alias(tid: ::std::os::raw::c_int, alias: *mut atom_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_thread_attach_engine(attr: *mut PL_thread_attr_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_thread_destroy_engine() -> bool;
}
unsafe extern "C" {
    pub fn PL_thread_at_exit(
        function: ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>,
        closure: *mut ::std::os::raw::c_void,
        global: bool,
    ) -> bool;
}
unsafe extern "C" {
    pub fn PL_thread_raise(tid: ::std::os::raw::c_int, sig: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_current_engine() -> PL_engine_t;
}
unsafe extern "C" {
    pub fn PL_create_engine(attributes: *mut PL_thread_attr_t) -> PL_engine_t;
}
unsafe extern "C" {
    pub fn PL_set_engine(engine: PL_engine_t, old: *mut PL_engine_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_destroy_engine(engine: PL_engine_t) -> bool;
}
unsafe extern "C" {
    pub fn _PL_switch_engine(e: PL_engine_t) -> PL_engine_t;
}
unsafe extern "C" {
    pub fn _PL_reset_engine(old: PL_engine_t) -> PL_engine_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_table {
    _unused: [u8; 0],
}
pub type hash_table_t = *mut __PL_table;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_table_enum {
    _unused: [u8; 0],
}
pub type hash_table_enum_t = *mut __PL_table_enum;
pub type table_key_t = u64;
pub type table_value_t = u64;
unsafe extern "C" {
    pub fn PL_new_hash_table(
        size: usize,
        free_symbol: ::std::option::Option<unsafe extern "C" fn(n: table_key_t, v: table_value_t)>,
    ) -> hash_table_t;
}
unsafe extern "C" {
    pub fn PL_free_hash_table(table: hash_table_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_lookup_hash_table(table: hash_table_t, key: table_key_t) -> table_value_t;
}
unsafe extern "C" {
    pub fn PL_add_hash_table(
        table: hash_table_t,
        key: table_key_t,
        value: table_value_t,
        flags: ::std::os::raw::c_int,
    ) -> table_value_t;
}
unsafe extern "C" {
    pub fn PL_del_hash_table(table: hash_table_t, key: table_key_t) -> table_value_t;
}
unsafe extern "C" {
    pub fn PL_clear_hash_table(table: hash_table_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_new_hash_table_enum(table: hash_table_t) -> hash_table_enum_t;
}
unsafe extern "C" {
    pub fn PL_free_hash_table_enum(e: hash_table_enum_t);
}
unsafe extern "C" {
    pub fn PL_advance_hash_table_enum(
        e: hash_table_enum_t,
        key: *mut table_key_t,
        value: *mut table_value_t,
    ) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PL_prof_type_t {
    pub unify: ::std::option::Option<
        unsafe extern "C" fn(t: term_t, handle: *mut ::std::os::raw::c_void) -> bool,
    >,
    pub get: ::std::option::Option<
        unsafe extern "C" fn(t: term_t, handle: *mut *mut ::std::os::raw::c_void) -> bool,
    >,
    pub activate: ::std::option::Option<unsafe extern "C" fn(active: bool)>,
    pub release: ::std::option::Option<unsafe extern "C" fn(handle: *mut ::std::os::raw::c_void)>,
    pub dummy: [*mut ::std::os::raw::c_void; 4usize],
    pub magic: isize,
}
unsafe extern "C" {
    pub fn PL_register_profile_type(type_: *mut PL_prof_type_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_prof_call(
        handle: *mut ::std::os::raw::c_void,
        type_: *mut PL_prof_type_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn PL_prof_exit(node: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn PL_prolog_debug(topic: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn PL_prolog_nodebug(topic: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct xpceref_t {
    pub type_: ::std::os::raw::c_int,
    pub value: xpceref_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union xpceref_t__bindgen_ty_1 {
    pub i: usize,
    pub a: atom_t,
}
unsafe extern "C" {
    pub fn _PL_get_xpce_reference(t: term_t, ref_: *mut xpceref_t) -> bool;
}
unsafe extern "C" {
    pub fn _PL_unify_xpce_reference(t: term_t, ref_: *mut xpceref_t) -> bool;
}
unsafe extern "C" {
    pub fn _PL_put_xpce_reference_i(t: term_t, r: usize) -> bool;
}
unsafe extern "C" {
    pub fn _PL_put_xpce_reference_a(t: term_t, name: atom_t) -> bool;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pl_context_t {
    pub ld: PL_engine_t,
    pub qf: *mut __PL_queryFrame,
    pub fr: *mut __PL_localFrame,
    pub pc: *mut __PL_code,
    pub reserved: [*mut ::std::os::raw::c_void; 10usize],
}
unsafe extern "C" {
    pub fn PL_get_context(c: *mut pl_context_t, thead_id: ::std::os::raw::c_int) -> bool;
}
unsafe extern "C" {
    pub fn PL_step_context(c: *mut pl_context_t) -> bool;
}
unsafe extern "C" {
    pub fn PL_describe_context(
        c: *mut pl_context_t,
        buf: *mut ::std::os::raw::c_char,
        len: usize,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_queryFrame {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __PL_localFrame {
    pub _address: u8,
}
